<<<<<<< HEAD
Dt:
  class_weight: null
  criterion: entropy
  max_depth: 10
  max_leaf_nodes: null
  min_samples_leaf: 2
  min_samples_split: 4
Lr:
  C: 0.1
  class_weight: null
  penalty: l2
  solver: newton-cholesky
RF:
  bootstrap: true
  class_weight: null
  criterion: log_loss
  max_depth: 10
  min_samples_leaf: 1
  min_samples_split: 3
  n_estimators: 100
  oob_score: false
knn:
  n_neighbors: 15
  weights: uniform
xgboost:
  colsample_bytree: 0.6
  gamma: 0.2
  learning_rate: 0.1
  max_depth: 3
  n_estimators: 100
  subsample: 0.8
=======
{}
>>>>>>> model_training
